Testname: files-python-general
References: Debian Bug#608810, Debian Bug#756005
Check: documentation
